package org.openmetadata.hackathon.extendprofiler.export;

import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class HtmlResultWriter {

    private static final Logger log = LoggerFactory.getLogger(HtmlResultWriter.class);
    private final String outputPath;

    public HtmlResultWriter(String outputPath) {
        this.outputPath = outputPath;
    }

    public void write(List<ProfileResult> results) throws IOException {

        int totalColumns = 0;
        int totalMetrics = 0;
        for (ProfileResult r : results) {
            totalColumns += r.getColumnCount();
            totalMetrics += r.getTableMetrics().size();
            for (Map<String, Double> cm : r.getColumnMetrics().values()) {
                totalMetrics += cm.size();
            }
        }

        try (Writer w = new FileWriter(outputPath)) {

            // --- HTML head + CSS ---
            w.write("<!DOCTYPE html>\n<html>\n<head>\n");
            w.write("<meta charset=\"UTF-8\">\n");
            w.write("<title>Profiler Report</title>\n");
            w.write("<style>\n");
            w.write(CSS);
            w.write("</style>\n</head>\n<body>\n");

            // --- summary bar ---
            w.write("<div class=\"summary\">\n");
            w.write("  <h1>OpenMetadata Extended Profiler Report</h1>\n");
            w.write("  <p>" + results.size() + " tables | "
                    + totalColumns + " columns | "
                    + totalMetrics + " metrics computed</p>\n");
            w.write("</div>\n");

            // --- per-table cards ---
            for (ProfileResult r : results) {
                writeTableCard(w, r);
            }

            w.write("<footer>Generated by extend-profilers-openmetadata</footer>\n");
            w.write("</body>\n</html>\n");

        } catch (IOException e) {
            log.error("Error writing HTML results", e);
            throw e;
        }

        log.info("Wrote HTML report to {}", outputPath);
    }

    private void writeTableCard(Writer w, ProfileResult r) throws IOException {
        String ts = Instant.ofEpochMilli(r.getTimestamp())
                .atZone(ZoneId.systemDefault())
                .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        w.write("<div class=\"card\">\n");
        w.write("  <h2>" + esc(r.getTableFqn()) + "</h2>\n");
        w.write("  <p class=\"meta\">" + r.getRowCount() + " rows &middot; "
                + r.getColumnCount() + " columns &middot; " + ts + "</p>\n");

        // table-level metrics
        if (!r.getTableMetrics().isEmpty()) {
            w.write("  <h3>Table-level metrics</h3>\n");
            w.write("  <table><tr><th>Metric</th><th>Value</th><th>Interpretation</th></tr>\n");
            for (Map.Entry<String, Double> e : r.getTableMetrics().entrySet()) {
                String cls = rate(e.getKey(), e.getValue());
                w.write("  <tr><td>" + esc(e.getKey()) + "</td>"
                        + "<td class=\"" + cls + "\">" + fmt(e.getValue()) + "</td>"
                        + "<td class=\"interp\">" + interpret(e.getKey(), e.getValue()) + "</td></tr>\n");
            }
            w.write("  </table>\n");
        }

        // column-level metrics
        if (!r.getColumnMetrics().isEmpty()) {
            List<String> metricNames = r.allMetricNames();

            w.write("  <h3>Column-level metrics</h3>\n");
            w.write("  <table><tr><th>Column</th>");
            for (String m : metricNames) {
                w.write("<th>" + esc(m) + "</th>");
            }
            w.write("</tr>\n");

            for (Map.Entry<String, Map<String, Double>> col : r.getColumnMetrics().entrySet()) {
                w.write("  <tr><td class=\"col-name\">" + esc(col.getKey()) + "</td>");
                for (String m : metricNames) {
                    Double val = col.getValue().get(m);
                    if (val != null) {
                        String cls = rate(m, val);
                        w.write("<td class=\"" + cls + "\" title=\""
                                + esc(interpret(m, val)) + "\">" + fmt(val) + "</td>");
                    } else {
                        w.write("<td class=\"na\">&mdash;</td>");
                    }
                }
                w.write("</tr>\n");
            }
            w.write("  </table>\n");
        }

        w.write("</div>\n");
    }

    // color rating based on metric thresholds
    public static String rate(String metric, double value) {
        switch (metric.toLowerCase()) {
            case "kurtosis":
                if (Math.abs(value) > 5) return "bad";
                if (Math.abs(value) > 2) return "warn";
                return "good";
            case "skewness":
                if (Math.abs(value) > 2) return "bad";
                if (Math.abs(value) > 1) return "warn";
                return "good";
            case "valueage":
                if (value > 1000) return "bad";
                if (value > 168) return "warn";
                return "good";
            case "seasonality":
                return value > 0 ? "good" : "neutral";
            default:
                return "neutral";
        }
    }

    // human-readable interpretation
    public static String interpret(String metric, double value) {
        switch (metric.toLowerCase()) {
            case "entropy":
                if (value < 1) return "Very low diversity — nearly all values identical";
                if (value < 3) return "Moderate diversity";
                return "High diversity — values well spread";
            case "relativeentropy":
                if (value < 0.5) return "Distribution roughly balanced";
                if (value < 2) return "Some concentration in certain values";
                return "Significant concentration — few values dominate";
            case "kurtosis":
                if (value > 5) return "Heavy outliers — investigate extreme values";
                if (value > 2) return "Moderate tail heaviness — some outliers likely";
                if (value < -2) return "Unusually uniform — possible truncation";
                return "Normal tail behavior";
            case "skewness":
                if (value > 2) return "Heavily right-skewed — long tail of large values";
                if (value > 1) return "Moderately right-skewed";
                if (value < -2) return "Heavily left-skewed — long tail of small values";
                if (value < -1) return "Moderately left-skewed";
                return "Roughly symmetric";
            case "seasonality":
                if (value == 0) return "No repeating pattern detected";
                return "Dominant cycle every " + (int) value + " data points";
            case "valueage":
                if (value > 1000) return "Stale data (" + (int) value + "h) — pipeline may be broken";
                if (value > 168) return "Data is " + (int) value + "h old — over a week";
                if (value > 24) return "Data is " + (int) value + "h old";
                return "Fresh data (" + String.format("%.1f", value) + "h old)";
            default:
                return fmt(value);
        }
    }

    private static String fmt(double value) {
        if (value == (long) value) return Long.toString((long) value);
        return String.format("%.4f", value);
    }

    private static String esc(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace("\"", "&quot;");
    }

    private static final String CSS = ""
            + "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;\n"
            + "       background: #f5f6fa; color: #2d3436; margin: 0; padding: 24px; }\n"
            + ".summary { text-align: center; padding: 24px 0; }\n"
            + ".summary h1 { color: #6c5ce7; margin-bottom: 8px; }\n"
            + ".summary p { color: #636e72; }\n"
            + ".card { background: #fff; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.07);\n"
            + "        padding: 24px; margin-bottom: 20px; }\n"
            + ".card h2 { font-size: 1.1em; word-break: break-all; }\n"
            + ".meta { font-size: 0.85em; color: #636e72; margin: 4px 0 12px; }\n"
            + "h3 { font-size: 0.9em; color: #636e72; margin: 14px 0 6px; }\n"
            + "table { width: 100%; border-collapse: collapse; font-size: 0.88em; }\n"
            + "th { background: #dfe6e9; text-align: left; padding: 8px 10px; font-weight: 600; }\n"
            + "td { padding: 7px 10px; border-bottom: 1px solid #f0f0f0; }\n"
            + ".col-name { font-weight: 600; }\n"
            + ".good { background: #00b89420; color: #00b894; font-weight: 600; }\n"
            + ".warn { background: #fdcb6e30; color: #e17055; font-weight: 600; }\n"
            + ".bad  { background: #d6336120; color: #d63361; font-weight: 600; }\n"
            + ".neutral { color: #636e72; }\n"
            + ".na { color: #b2bec3; text-align: center; }\n"
            + ".interp { font-size: 0.85em; color: #636e72; }\n"
            + "footer { text-align: center; color: #b2bec3; font-size: 0.8em; padding: 20px 0; }\n";
}
